<?php

use App\Support\Migrations\EnablesRowLevelSecurity;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * The server-side record of every accepted sync_op, backing the pull
 * cursor docs/sync-plan.md's Q9 decided: a device pulls "everything with
 * seq greater than the last one I saw," never a client timestamp — the
 * exact same read-then-write-counter mistake `audit_log.seq` was fixed
 * away from would recur here if this used anything but a real identity
 * column. See api/docs/rls.md's "Sequence-backed audit ordering".
 *
 * Deliberately not the same table as `sync_ops` (which already exists —
 * see 2026_09_11_170027_create_sync_ops_table.php, docs/schema.md's v2
 * additions): `sync_ops` is the client's own outbound queue shape
 * (op_id, entity, entity_id, action, payload, device_id, created_at,
 * synced_at), mirrored server-side but never yet written to by any
 * endpoint. `sync_ledger` is a different, additive concept — a lean,
 * ordered, org-scoped receipt of what actually landed, carrying the
 * resulting `rev` and the resolved actor, not the payload. No conflict
 * with docs/schema.md's existing sync_ops definition: this migration adds
 * a new table, it does not touch or redefine that one. (Whether a future
 * push endpoint's implementation ends up writing into the existing
 * `sync_ops` table too, as a payload/idempotency store, alongside writing
 * here, is that endpoint's decision — out of scope for this migration,
 * which builds no endpoint.)
 *
 * RLS shape matches `audit_log` exactly, per instruction: FORCE,
 * org-scoped, append-only. Split SELECT/INSERT policies rather than one
 * combined USING+WITH CHECK, and no UPDATE/DELETE policy at all — with
 * RLS forced and no matching policy, every UPDATE/DELETE affects zero
 * rows, so the ledger is immutable by construction, the same as
 * audit_log. `EnablesRowLevelSecurity` still grants clintra_app the
 * standard SELECT/INSERT/UPDATE/DELETE (matching every other table,
 * including audit_log) — harmless for UPDATE/DELETE precisely because no
 * policy ever lets either succeed.
 */
return new class extends Migration
{
    use EnablesRowLevelSecurity;

    public function up(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE sync_ledger (
                seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                op_id uuid NOT NULL,
                org_id uuid NOT NULL REFERENCES organizations (id) ON DELETE RESTRICT,
                entity text NOT NULL,
                entity_id uuid NOT NULL,
                rev integer NOT NULL,
                actor_membership_id uuid NOT NULL REFERENCES memberships (id) ON DELETE RESTRICT,
                device_id uuid NOT NULL REFERENCES device (id) ON DELETE RESTRICT,
                applied_at timestamptz NOT NULL
            )
        SQL);

        // op_id is the idempotency key the brief describes ("the server
        // ignores any duplicate op_id") — a UNIQUE constraint makes a
        // second insert attempt for the same op a real, catchable
        // constraint violation, not something application code has to
        // check for separately.
        DB::statement('CREATE UNIQUE INDEX sync_ledger_op_id_unique ON sync_ledger (op_id)');
        DB::statement('CREATE INDEX sync_ledger_org_id_index ON sync_ledger (org_id)');
        DB::statement('CREATE INDEX sync_ledger_entity_entity_id_index ON sync_ledger (entity, entity_id)');

        $this->enableRowLevelSecurity('sync_ledger');

        DB::statement('CREATE POLICY sync_ledger_select ON sync_ledger FOR SELECT USING (org_id = current_org())');
        DB::statement('CREATE POLICY sync_ledger_insert ON sync_ledger FOR INSERT WITH CHECK (org_id = current_org())');
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS sync_ledger');
    }
};
