<?php

use App\Support\Migrations\EnablesRowLevelSecurity;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// See docs/schema.md's v10 additions. Backs real device registration
// (docs/auth-plan.md's Layer 1, Q2 resolution) — a one-time credential an
// owner types into a new device. code_hash is SHA-256; the plaintext is
// never stored (see api/docs/rls.md's registration section).
return new class extends Migration
{
    use EnablesRowLevelSecurity;

    public function up(): void
    {
        Schema::create('activation_codes', function (Blueprint $table) {
            // uuid v4, generated by the CLI command that mints this row —
            // never by Postgres.
            $table->uuid('id')->primary();
            $table->foreignUuid('org_id')->constrained('organizations')->restrictOnDelete();
            $table->foreignUuid('location_id')->constrained('locations')->restrictOnDelete();
            // SHA-256 hex digest of the plaintext code — same convention as
            // Sanctum's own personal_access_tokens.token, not Argon2id: this
            // is a high-entropy random secret, not a low-entropy PIN, so a
            // slow KDF buys nothing but latency (see PinHash's doc comment
            // for the contrasting case that DOES need one).
            $table->string('code_hash')->unique();
            $table->timestampTz('expires_at');
            $table->timestampTz('used_at')->nullable();
            $table->foreignUuid('used_by_device_id')->nullable()->constrained('device')->restrictOnDelete();
            $table->timestampTz('created_at');

            $table->index('org_id');
        });

        $this->enableRowLevelSecurity('activation_codes');

        // Same policy shape as every other org-scoped table, for
        // consistency — nothing currently reads or writes activation_codes
        // through clintra_app at all (creation and verification both go
        // through SECURITY DEFINER functions; see the provisioning and
        // device-registration migrations), so this policy is currently
        // unexercised but keeps the table from being a silent RLS gap if
        // that ever changes.
        DB::statement('CREATE POLICY activation_codes_scope ON activation_codes USING (org_id = current_org()) WITH CHECK (org_id = current_org())');
    }

    public function down(): void
    {
        Schema::dropIfExists('activation_codes');
    }
};
