<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Every provisioning function computed audit_log.seq with
 * `SELECT COALESCE(MAX(seq), 0) + 1` — the same class of bug the web side
 * already fixed for its own local counter (commit 236e2e2, monotonic undo
 * ordering): two concurrent transactions can read the same MAX and compute
 * the same next value. audit_log.seq carries a UNIQUE constraint
 * (2026_09_11_170021_create_audit_log_table.php), so the actual failure
 * mode here isn't silent ambiguity — it's a unique-violation that rolls
 * back the *entire* transaction, including the row the audit entry was
 * for. A concurrent registration or provisioning call could fail outright
 * over an unrelated table's constraint.
 *
 * Fixed by making seq a real Postgres identity column
 * (`GENERATED BY DEFAULT AS IDENTITY`, started above the current max so
 * existing rows' seq values are undisturbed and never collide with a
 * freshly-generated one) — `nextval()` is atomic under concurrency by
 * construction, which a read-then-write pair never is. Every INSERT INTO
 * audit_log across all three provisioning functions now omits `seq`
 * entirely, letting Postgres assign it.
 *
 * This also means none of the three provisioning roles need SELECT on
 * audit_log any more — SELECT MAX(seq) was the only reason they had it
 * (api/docs/rls.md's "One role per provisioning function"). Revoked below.
 * Confirmed empirically before doing so: an identity column's underlying
 * sequence needs no separate USAGE grant for a role that already has
 * INSERT on the table — Postgres treats the sequence as an implicit part
 * of the table for this purpose, unlike a role calling nextval() directly.
 * `clintra_app` is not touched here — this migration only revokes SELECT
 * from the three provisioning roles. (Corrected: an earlier version of
 * this comment claimed clintra_app had no grant on audit_log at all,
 * which was wrong — it already held full SELECT/INSERT/UPDATE/DELETE via
 * the standard EnablesRowLevelSecurity grant, same as every other table
 * — see 2026_09_11_170021_create_audit_log_table.php. The absence of any
 * UPDATE/DELETE *policy* is what made those two inert, not the absence of
 * the grant; 2026_09_12_000015_revoke_inert_write_grants.php later
 * revokes them explicitly so both layers hold independently.)
 *
 * See docs/schema.md's new "v11 additions" section for the column's
 * documented shape, and api/docs/rls.md for the concurrency test.
 */
return new class extends Migration
{
    public function up(): void
    {
        // START WITH one past the current max: existing rows keep their
        // seq values untouched, and the first freshly-generated value can
        // never collide with one already on disk (including in an
        // already-provisioned database, not just a fresh one).
        DB::statement(<<<'SQL'
            DO $$
            DECLARE
                v_next bigint;
            BEGIN
                SELECT COALESCE(MAX(seq), 0) + 1 INTO v_next FROM audit_log;
                EXECUTE format(
                    'ALTER TABLE audit_log ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
                    v_next
                );
            END $$;
        SQL);

        DB::statement('SET ROLE clintra_provision');
        DB::statement('DROP FUNCTION IF EXISTS provision_organization(jsonb)');
        DB::statement(<<<'SQL'
            CREATE FUNCTION provision_organization(payload jsonb) RETURNS jsonb
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = public, pg_temp
            AS $$
            DECLARE
                v_allowed_keys text[] := ARRAY[
                    'org_id', 'org_name', 'plan_tier',
                    'location_id', 'location_name', 'location_address', 'location_phone', 'location_org_id',
                    'user_id', 'user_full_name', 'user_phone',
                    'practitioner_id', 'practitioner_title', 'practitioner_org_id', 'specialty_id',
                    'practitioner_location_id',
                    'membership_id', 'membership_org_id', 'role', 'location_scope', 'practitioner_scope',
                    'pin_hash', 'pin_salt',
                    'activation_code_id', 'activation_code_hash', 'activation_code_expires_at',
                    'audit_organization_id', 'audit_location_id', 'audit_user_id', 'audit_practitioner_id',
                    'audit_practitioner_location_id', 'audit_membership_id', 'audit_activation_code_id'
                ];
                v_unknown_keys text[];
                v_key text;

                v_org_id uuid;
                v_org_name text;
                v_plan_tier text;
                v_location_id uuid;
                v_location_name text;
                v_location_address text;
                v_location_phone text;
                v_user_id uuid;
                v_user_full_name text;
                v_user_phone text;
                v_user_is_new boolean := true;
                v_existing_user_id uuid;
                v_practitioner_id uuid;
                v_practitioner_title text;
                v_specialty_id uuid;
                v_practitioner_location_id uuid;
                v_membership_id uuid;
                v_pin_hash text;
                v_pin_salt text;
                v_activation_code_id uuid;
                v_activation_code_hash text;
                v_activation_code_expires_at timestamptz;
                v_now timestamptz := now();
            BEGIN
                SELECT array_agg(k) INTO v_unknown_keys
                FROM jsonb_object_keys(payload) AS k
                WHERE k <> ALL (v_allowed_keys);

                IF v_unknown_keys IS NOT NULL THEN
                    RAISE EXCEPTION 'provision_organization: unknown payload key(s): %', array_to_string(v_unknown_keys, ', ')
                        USING ERRCODE = '22023';
                END IF;

                FOREACH v_key IN ARRAY v_allowed_keys LOOP
                    IF NOT jsonb_exists(payload, v_key) OR jsonb_typeof(payload -> v_key) = 'null' THEN
                        RAISE EXCEPTION 'provision_organization: missing or null required key "%"', v_key
                            USING ERRCODE = '22023';
                    END IF;
                END LOOP;

                IF payload->>'role' <> 'owner' THEN
                    RAISE EXCEPTION 'provision_organization: role must be "owner"' USING ERRCODE = '22023';
                END IF;
                IF payload->>'location_scope' <> 'all' THEN
                    RAISE EXCEPTION 'provision_organization: location_scope must be "all"' USING ERRCODE = '22023';
                END IF;
                IF payload->>'practitioner_scope' <> 'all' THEN
                    RAISE EXCEPTION 'provision_organization: practitioner_scope must be "all"' USING ERRCODE = '22023';
                END IF;

                IF payload->>'pin_hash' !~ '^[0-9a-f]{64}$' THEN
                    RAISE EXCEPTION 'provision_organization: pin_hash must be 64 lowercase hex characters' USING ERRCODE = '22023';
                END IF;
                IF payload->>'pin_salt' !~ '^[0-9a-f]{32}$' THEN
                    RAISE EXCEPTION 'provision_organization: pin_salt must be 32 lowercase hex characters' USING ERRCODE = '22023';
                END IF;

                IF payload->>'activation_code_hash' !~ '^[0-9a-f]{64}$' THEN
                    RAISE EXCEPTION 'provision_organization: activation_code_hash must be 64 lowercase hex characters' USING ERRCODE = '22023';
                END IF;

                IF payload->>'location_phone' !~ '^\+[1-9]\d{1,14}$' THEN
                    RAISE EXCEPTION 'provision_organization: location_phone must be a non-empty E.164 number' USING ERRCODE = '22023';
                END IF;
                IF payload->>'user_phone' !~ '^\+[1-9]\d{1,14}$' THEN
                    RAISE EXCEPTION 'provision_organization: user_phone must be a non-empty E.164 number' USING ERRCODE = '22023';
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM specialty_templates
                    WHERE id = (payload->>'specialty_id')::uuid AND org_id IS NULL
                ) THEN
                    RAISE EXCEPTION 'provision_organization: specialty_id must reference an existing system-wide specialty_templates row' USING ERRCODE = '22023';
                END IF;

                v_org_id := (payload->>'org_id')::uuid;

                IF (payload->>'location_org_id')::uuid <> v_org_id
                    OR (payload->>'practitioner_org_id')::uuid <> v_org_id
                    OR (payload->>'membership_org_id')::uuid <> v_org_id
                THEN
                    RAISE EXCEPTION 'provision_organization: location_org_id, practitioner_org_id and membership_org_id must all equal org_id' USING ERRCODE = '22023';
                END IF;

                v_activation_code_expires_at := (payload->>'activation_code_expires_at')::timestamptz;
                IF v_activation_code_expires_at <= v_now THEN
                    RAISE EXCEPTION 'provision_organization: activation_code_expires_at must be in the future' USING ERRCODE = '22023';
                END IF;

                v_org_name := payload->>'org_name';
                v_plan_tier := payload->>'plan_tier';
                v_location_id := (payload->>'location_id')::uuid;
                v_location_name := payload->>'location_name';
                v_location_address := payload->>'location_address';
                v_location_phone := payload->>'location_phone';
                v_user_full_name := payload->>'user_full_name';
                v_user_phone := payload->>'user_phone';
                v_practitioner_id := (payload->>'practitioner_id')::uuid;
                v_practitioner_title := payload->>'practitioner_title';
                v_specialty_id := (payload->>'specialty_id')::uuid;
                v_practitioner_location_id := (payload->>'practitioner_location_id')::uuid;
                v_membership_id := (payload->>'membership_id')::uuid;
                v_pin_hash := payload->>'pin_hash';
                v_pin_salt := payload->>'pin_salt';
                v_activation_code_id := (payload->>'activation_code_id')::uuid;
                v_activation_code_hash := payload->>'activation_code_hash';

                INSERT INTO organizations (id, name, plan_tier, created_at)
                VALUES (v_org_id, v_org_name, v_plan_tier, v_now);

                INSERT INTO locations (id, org_id, name, address, phone, is_active)
                VALUES (v_location_id, v_org_id, v_location_name, v_location_address, v_location_phone, true);

                SELECT id INTO v_existing_user_id FROM users WHERE phone = v_user_phone;
                IF FOUND THEN
                    v_user_id := v_existing_user_id;
                    v_user_is_new := false;
                ELSE
                    v_user_id := (payload->>'user_id')::uuid;
                    INSERT INTO users (id, full_name, phone, email, is_active)
                    VALUES (v_user_id, v_user_full_name, v_user_phone, NULL, true);
                END IF;

                INSERT INTO practitioners (id, org_id, user_id, full_name, specialty_id, title, is_active)
                VALUES (v_practitioner_id, v_org_id, v_user_id, v_user_full_name, v_specialty_id, v_practitioner_title, true);

                INSERT INTO practitioner_locations (id, practitioner_id, location_id, is_active)
                VALUES (v_practitioner_location_id, v_practitioner_id, v_location_id, true);

                INSERT INTO memberships (
                    id, user_id, org_id, role, location_scope, practitioner_scope,
                    practitioner_id, pin_hash, pin_salt, is_active
                )
                VALUES (
                    v_membership_id, v_user_id, v_org_id,
                    'owner', 'all', 'all', NULL,
                    v_pin_hash, v_pin_salt, true
                );

                INSERT INTO activation_codes (id, org_id, location_id, code_hash, expires_at, used_at, used_by_device_id, created_at)
                VALUES (v_activation_code_id, v_org_id, v_location_id, v_activation_code_hash, v_activation_code_expires_at, NULL, NULL, v_now);

                -- seq is no longer computed here — omitted from every
                -- INSERT INTO audit_log below, so Postgres assigns it via
                -- the identity column's own sequence (atomic under
                -- concurrency, unlike the SELECT MAX(seq)+1 this replaces).
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_organization_id')::uuid, v_org_id, v_membership_id, 'organizations', v_org_id, 'create', NULL,
                    jsonb_build_object('id', v_org_id, 'name', v_org_name, 'plan_tier', v_plan_tier, 'created_at', v_now),
                    v_now
                );

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_location_id')::uuid, v_org_id, v_membership_id, 'locations', v_location_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_location_id, 'org_id', v_org_id, 'name', v_location_name,
                        'address', v_location_address, 'phone', v_location_phone, 'is_active', true
                    ),
                    v_now
                );

                IF v_user_is_new THEN
                    INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                    VALUES (
                        (payload->>'audit_user_id')::uuid, v_org_id, v_membership_id, 'users', v_user_id, 'create', NULL,
                        jsonb_build_object('id', v_user_id, 'full_name', v_user_full_name, 'phone', v_user_phone, 'email', NULL, 'is_active', true),
                        v_now
                    );
                END IF;

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_practitioner_id')::uuid, v_org_id, v_membership_id, 'practitioners', v_practitioner_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_practitioner_id, 'org_id', v_org_id, 'user_id', v_user_id, 'full_name', v_user_full_name,
                        'specialty_id', v_specialty_id, 'title', v_practitioner_title, 'is_active', true
                    ),
                    v_now
                );

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_practitioner_location_id')::uuid, v_org_id, v_membership_id, 'practitioner_locations', v_practitioner_location_id, 'create', NULL,
                    jsonb_build_object('id', v_practitioner_location_id, 'practitioner_id', v_practitioner_id, 'location_id', v_location_id, 'is_active', true),
                    v_now
                );

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_membership_id')::uuid, v_org_id, v_membership_id, 'memberships', v_membership_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_membership_id, 'user_id', v_user_id, 'org_id', v_org_id, 'role', 'owner',
                        'location_scope', 'all', 'practitioner_scope', 'all', 'practitioner_id', NULL, 'is_active', true
                    ),
                    v_now
                );

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_activation_code_id')::uuid, v_org_id, v_membership_id, 'activation_codes', v_activation_code_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_activation_code_id, 'org_id', v_org_id, 'location_id', v_location_id,
                        'expires_at', v_activation_code_expires_at, 'used_at', NULL, 'used_by_device_id', NULL
                    ),
                    v_now
                );

                RETURN jsonb_build_object(
                    'organization_id', v_org_id,
                    'location_id', v_location_id,
                    'user_id', v_user_id,
                    'user_is_new', v_user_is_new,
                    'practitioner_id', v_practitioner_id,
                    'practitioner_location_id', v_practitioner_location_id,
                    'membership_id', v_membership_id,
                    'activation_code_id', v_activation_code_id
                );
            END;
            $$
        SQL);
        DB::statement('REVOKE EXECUTE ON FUNCTION provision_organization(jsonb) FROM PUBLIC');
        DB::statement('GRANT EXECUTE ON FUNCTION provision_organization(jsonb) TO clintra_owner');
        DB::statement('RESET ROLE');

        DB::statement('SET ROLE clintra_mint');
        DB::statement('DROP FUNCTION IF EXISTS mint_activation_code(jsonb)');
        DB::statement(<<<'SQL'
            CREATE FUNCTION mint_activation_code(payload jsonb) RETURNS jsonb
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = public, pg_temp
            AS $$
            DECLARE
                v_allowed_keys text[] := ARRAY['id', 'org_id', 'location_id', 'code_hash', 'expires_at', 'audit_id'];
                v_unknown_keys text[];
                v_key text;

                v_id uuid;
                v_org_id uuid;
                v_location_id uuid;
                v_code_hash text;
                v_expires_at timestamptz;
                v_owner_membership_id uuid;
                v_now timestamptz := now();
            BEGIN
                SELECT array_agg(k) INTO v_unknown_keys
                FROM jsonb_object_keys(payload) AS k
                WHERE k <> ALL (v_allowed_keys);

                IF v_unknown_keys IS NOT NULL THEN
                    RAISE EXCEPTION 'mint_activation_code: unknown payload key(s): %', array_to_string(v_unknown_keys, ', ')
                        USING ERRCODE = '22023';
                END IF;

                FOREACH v_key IN ARRAY v_allowed_keys LOOP
                    IF NOT jsonb_exists(payload, v_key) OR jsonb_typeof(payload -> v_key) = 'null' THEN
                        RAISE EXCEPTION 'mint_activation_code: missing or null required key "%"', v_key
                            USING ERRCODE = '22023';
                    END IF;
                END LOOP;

                v_org_id := (payload->>'org_id')::uuid;
                v_location_id := (payload->>'location_id')::uuid;
                v_code_hash := payload->>'code_hash';
                v_expires_at := (payload->>'expires_at')::timestamptz;

                IF v_code_hash !~ '^[0-9a-f]{64}$' THEN
                    RAISE EXCEPTION 'mint_activation_code: code_hash must be 64 lowercase hex characters' USING ERRCODE = '22023';
                END IF;

                IF v_expires_at <= v_now THEN
                    RAISE EXCEPTION 'mint_activation_code: expires_at must be in the future' USING ERRCODE = '22023';
                END IF;

                IF NOT EXISTS (SELECT 1 FROM locations WHERE id = v_location_id AND org_id = v_org_id) THEN
                    RAISE EXCEPTION 'mint_activation_code: location_id must belong to org_id' USING ERRCODE = '22023';
                END IF;

                SELECT id INTO v_owner_membership_id
                FROM memberships
                WHERE org_id = v_org_id AND role = 'owner' AND is_active = true
                ORDER BY id
                LIMIT 1;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'mint_activation_code: org_id has no active owner membership' USING ERRCODE = '22023';
                END IF;

                v_id := (payload->>'id')::uuid;

                INSERT INTO activation_codes (id, org_id, location_id, code_hash, expires_at, used_at, used_by_device_id, created_at)
                VALUES (v_id, v_org_id, v_location_id, v_code_hash, v_expires_at, NULL, NULL, v_now);

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_id')::uuid, v_org_id, v_owner_membership_id, 'activation_codes', v_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_id, 'org_id', v_org_id, 'location_id', v_location_id,
                        'expires_at', v_expires_at, 'used_at', NULL, 'used_by_device_id', NULL
                    ),
                    v_now
                );

                RETURN jsonb_build_object('id', v_id, 'org_id', v_org_id, 'location_id', v_location_id, 'expires_at', v_expires_at);
            END;
            $$
        SQL);
        DB::statement('REVOKE EXECUTE ON FUNCTION mint_activation_code(jsonb) FROM PUBLIC');
        DB::statement('GRANT EXECUTE ON FUNCTION mint_activation_code(jsonb) TO clintra_owner');
        DB::statement('RESET ROLE');

        DB::statement('SET ROLE clintra_register');
        DB::statement('DROP FUNCTION IF EXISTS register_device(jsonb)');
        DB::statement(<<<'SQL'
            CREATE FUNCTION register_device(payload jsonb) RETURNS jsonb
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = public, pg_temp
            AS $$
            DECLARE
                v_allowed_keys text[] := ARRAY['device_id', 'phone', 'code_hash', 'audit_device_id', 'audit_code_used_id'];
                v_unknown_keys text[];
                v_key text;

                v_device_id uuid;
                v_phone text;
                v_code_hash text;

                v_code_id uuid;
                v_code_org_id uuid;
                v_code_location_id uuid;
                v_code_expires_at timestamptz;
                v_code_used_at timestamptz;

                v_membership_id uuid;
                v_updated_rows int;
                v_now timestamptz := now();

                v_organization jsonb;
                v_locations jsonb;
                v_practitioners jsonb;
                v_memberships jsonb;
            BEGIN
                IF payload->>'device_id' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
                    RAISE EXCEPTION 'register_device: device_id must be a well-formed uuid' USING ERRCODE = '22023';
                END IF;

                IF payload->>'phone' !~ '^\+[1-9]\d{1,14}$' THEN
                    RAISE EXCEPTION 'register_device: phone must be a non-empty E.164 number' USING ERRCODE = '22023';
                END IF;

                IF payload->>'code_hash' !~ '^[0-9a-f]{64}$' THEN
                    RAISE EXCEPTION 'register_device: code_hash must be 64 lowercase hex characters' USING ERRCODE = '22023';
                END IF;

                SELECT array_agg(k) INTO v_unknown_keys
                FROM jsonb_object_keys(payload) AS k
                WHERE k <> ALL (v_allowed_keys);

                IF v_unknown_keys IS NOT NULL THEN
                    RAISE EXCEPTION 'register_device: unknown payload key(s): %', array_to_string(v_unknown_keys, ', ')
                        USING ERRCODE = '22023';
                END IF;

                FOREACH v_key IN ARRAY v_allowed_keys LOOP
                    IF NOT jsonb_exists(payload, v_key) OR jsonb_typeof(payload -> v_key) = 'null' THEN
                        RAISE EXCEPTION 'register_device: missing or null required key "%"', v_key
                            USING ERRCODE = '22023';
                    END IF;
                END LOOP;

                v_device_id := (payload->>'device_id')::uuid;
                v_phone := payload->>'phone';
                v_code_hash := payload->>'code_hash';

                SELECT id, org_id, location_id, expires_at, used_at
                INTO v_code_id, v_code_org_id, v_code_location_id, v_code_expires_at, v_code_used_at
                FROM activation_codes
                WHERE code_hash = v_code_hash;

                IF NOT FOUND OR v_code_used_at IS NOT NULL OR v_code_expires_at <= v_now THEN
                    RAISE EXCEPTION 'register_device: registration failed';
                END IF;

                SELECT m.id INTO v_membership_id
                FROM memberships m
                JOIN users u ON u.id = m.user_id
                WHERE m.org_id = v_code_org_id
                  AND m.role = 'owner'
                  AND m.is_active = true
                  AND u.phone = v_phone
                LIMIT 1;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'register_device: registration failed';
                END IF;

                UPDATE activation_codes
                SET used_at = v_now
                WHERE id = v_code_id AND used_at IS NULL;

                GET DIAGNOSTICS v_updated_rows = ROW_COUNT;
                IF v_updated_rows = 0 THEN
                    RAISE EXCEPTION 'register_device: registration failed';
                END IF;

                INSERT INTO device (id, org_id, location_id, membership_id, registered_at)
                VALUES (v_device_id, v_code_org_id, v_code_location_id, v_membership_id, v_now);

                UPDATE activation_codes
                SET used_by_device_id = v_device_id
                WHERE id = v_code_id;

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_device_id')::uuid, v_code_org_id, v_membership_id, 'device', v_device_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_device_id, 'org_id', v_code_org_id, 'location_id', v_code_location_id,
                        'membership_id', v_membership_id, 'registered_at', v_now
                    ),
                    v_now
                );

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at)
                VALUES (
                    (payload->>'audit_code_used_id')::uuid, v_code_org_id, v_membership_id, 'activation_codes', v_code_id, 'update',
                    jsonb_build_object('used_at', NULL, 'used_by_device_id', NULL),
                    jsonb_build_object('used_at', v_now, 'used_by_device_id', v_device_id),
                    v_now
                );

                SELECT jsonb_build_object('id', id, 'name', name, 'plan_tier', plan_tier, 'created_at', created_at)
                INTO v_organization
                FROM organizations WHERE id = v_code_org_id;

                SELECT COALESCE(jsonb_agg(jsonb_build_object(
                    'id', id, 'org_id', org_id, 'name', name, 'address', address, 'phone', phone, 'is_active', is_active
                )), '[]'::jsonb)
                INTO v_locations
                FROM locations WHERE org_id = v_code_org_id;

                SELECT COALESCE(jsonb_agg(jsonb_build_object(
                    'id', id, 'org_id', org_id, 'user_id', user_id, 'full_name', full_name,
                    'specialty_id', specialty_id, 'title', title, 'is_active', is_active
                )), '[]'::jsonb)
                INTO v_practitioners
                FROM practitioners WHERE org_id = v_code_org_id;

                SELECT COALESCE(jsonb_agg(jsonb_build_object(
                    'id', id, 'user_id', user_id, 'org_id', org_id, 'role', role,
                    'location_scope', location_scope, 'practitioner_scope', practitioner_scope,
                    'practitioner_id', practitioner_id, 'pin_hash', pin_hash, 'pin_salt', pin_salt,
                    'is_active', is_active
                )), '[]'::jsonb)
                INTO v_memberships
                FROM memberships WHERE org_id = v_code_org_id;

                RETURN jsonb_build_object(
                    'device_id', v_device_id,
                    'org_id', v_code_org_id,
                    'location_id', v_code_location_id,
                    'membership_id', v_membership_id,
                    'organization', v_organization,
                    'locations', v_locations,
                    'practitioners', v_practitioners,
                    'memberships', v_memberships
                );
            END;
            $$
        SQL);
        DB::statement('REVOKE EXECUTE ON FUNCTION register_device(jsonb) FROM PUBLIC');
        DB::statement('GRANT EXECUTE ON FUNCTION register_device(jsonb) TO clintra_app');
        DB::statement('RESET ROLE');

        // SELECT MAX(seq) was the only reason any of the three roles ever
        // needed SELECT on audit_log — see api/docs/rls.md.
        DB::statement('REVOKE SELECT ON audit_log FROM clintra_provision');
        DB::statement('REVOKE SELECT ON audit_log FROM clintra_mint');
        DB::statement('REVOKE SELECT ON audit_log FROM clintra_register');
    }

    public function down(): void
    {
        DB::statement('GRANT SELECT ON audit_log TO clintra_provision');
        DB::statement('GRANT SELECT ON audit_log TO clintra_mint');
        DB::statement('GRANT SELECT ON audit_log TO clintra_register');

        DB::statement('ALTER TABLE audit_log ALTER COLUMN seq DROP IDENTITY IF EXISTS');

        // Restores each function to its exact pre-000010 body (explicit
        // SELECT MAX(seq)+1), matching 2026_09_12_000004's
        // provision_organization and 2026_09_12_000009's
        // mint_activation_code/register_device verbatim.
        DB::statement('SET ROLE clintra_provision');
        DB::statement('DROP FUNCTION IF EXISTS provision_organization(jsonb)');
        DB::statement(<<<'SQL'
            CREATE FUNCTION provision_organization(payload jsonb) RETURNS jsonb
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = public, pg_temp
            AS $$
            DECLARE
                v_allowed_keys text[] := ARRAY[
                    'org_id', 'org_name', 'plan_tier',
                    'location_id', 'location_name', 'location_address', 'location_phone', 'location_org_id',
                    'user_id', 'user_full_name', 'user_phone',
                    'practitioner_id', 'practitioner_title', 'practitioner_org_id', 'specialty_id',
                    'practitioner_location_id',
                    'membership_id', 'membership_org_id', 'role', 'location_scope', 'practitioner_scope',
                    'pin_hash', 'pin_salt',
                    'activation_code_id', 'activation_code_hash', 'activation_code_expires_at',
                    'audit_organization_id', 'audit_location_id', 'audit_user_id', 'audit_practitioner_id',
                    'audit_practitioner_location_id', 'audit_membership_id', 'audit_activation_code_id'
                ];
                v_unknown_keys text[];
                v_key text;

                v_org_id uuid;
                v_org_name text;
                v_plan_tier text;
                v_location_id uuid;
                v_location_name text;
                v_location_address text;
                v_location_phone text;
                v_user_id uuid;
                v_user_full_name text;
                v_user_phone text;
                v_user_is_new boolean := true;
                v_existing_user_id uuid;
                v_practitioner_id uuid;
                v_practitioner_title text;
                v_specialty_id uuid;
                v_practitioner_location_id uuid;
                v_membership_id uuid;
                v_pin_hash text;
                v_pin_salt text;
                v_activation_code_id uuid;
                v_activation_code_hash text;
                v_activation_code_expires_at timestamptz;
                v_seq bigint;
                v_now timestamptz := now();
            BEGIN
                SELECT array_agg(k) INTO v_unknown_keys
                FROM jsonb_object_keys(payload) AS k
                WHERE k <> ALL (v_allowed_keys);

                IF v_unknown_keys IS NOT NULL THEN
                    RAISE EXCEPTION 'provision_organization: unknown payload key(s): %', array_to_string(v_unknown_keys, ', ')
                        USING ERRCODE = '22023';
                END IF;

                FOREACH v_key IN ARRAY v_allowed_keys LOOP
                    IF NOT jsonb_exists(payload, v_key) OR jsonb_typeof(payload -> v_key) = 'null' THEN
                        RAISE EXCEPTION 'provision_organization: missing or null required key "%"', v_key
                            USING ERRCODE = '22023';
                    END IF;
                END LOOP;

                IF payload->>'role' <> 'owner' THEN
                    RAISE EXCEPTION 'provision_organization: role must be "owner"' USING ERRCODE = '22023';
                END IF;
                IF payload->>'location_scope' <> 'all' THEN
                    RAISE EXCEPTION 'provision_organization: location_scope must be "all"' USING ERRCODE = '22023';
                END IF;
                IF payload->>'practitioner_scope' <> 'all' THEN
                    RAISE EXCEPTION 'provision_organization: practitioner_scope must be "all"' USING ERRCODE = '22023';
                END IF;

                IF payload->>'pin_hash' !~ '^[0-9a-f]{64}$' THEN
                    RAISE EXCEPTION 'provision_organization: pin_hash must be 64 lowercase hex characters' USING ERRCODE = '22023';
                END IF;
                IF payload->>'pin_salt' !~ '^[0-9a-f]{32}$' THEN
                    RAISE EXCEPTION 'provision_organization: pin_salt must be 32 lowercase hex characters' USING ERRCODE = '22023';
                END IF;

                IF payload->>'activation_code_hash' !~ '^[0-9a-f]{64}$' THEN
                    RAISE EXCEPTION 'provision_organization: activation_code_hash must be 64 lowercase hex characters' USING ERRCODE = '22023';
                END IF;

                IF payload->>'location_phone' !~ '^\+[1-9]\d{1,14}$' THEN
                    RAISE EXCEPTION 'provision_organization: location_phone must be a non-empty E.164 number' USING ERRCODE = '22023';
                END IF;
                IF payload->>'user_phone' !~ '^\+[1-9]\d{1,14}$' THEN
                    RAISE EXCEPTION 'provision_organization: user_phone must be a non-empty E.164 number' USING ERRCODE = '22023';
                END IF;

                IF NOT EXISTS (
                    SELECT 1 FROM specialty_templates
                    WHERE id = (payload->>'specialty_id')::uuid AND org_id IS NULL
                ) THEN
                    RAISE EXCEPTION 'provision_organization: specialty_id must reference an existing system-wide specialty_templates row' USING ERRCODE = '22023';
                END IF;

                v_org_id := (payload->>'org_id')::uuid;

                IF (payload->>'location_org_id')::uuid <> v_org_id
                    OR (payload->>'practitioner_org_id')::uuid <> v_org_id
                    OR (payload->>'membership_org_id')::uuid <> v_org_id
                THEN
                    RAISE EXCEPTION 'provision_organization: location_org_id, practitioner_org_id and membership_org_id must all equal org_id' USING ERRCODE = '22023';
                END IF;

                v_activation_code_expires_at := (payload->>'activation_code_expires_at')::timestamptz;
                IF v_activation_code_expires_at <= v_now THEN
                    RAISE EXCEPTION 'provision_organization: activation_code_expires_at must be in the future' USING ERRCODE = '22023';
                END IF;

                v_org_name := payload->>'org_name';
                v_plan_tier := payload->>'plan_tier';
                v_location_id := (payload->>'location_id')::uuid;
                v_location_name := payload->>'location_name';
                v_location_address := payload->>'location_address';
                v_location_phone := payload->>'location_phone';
                v_user_full_name := payload->>'user_full_name';
                v_user_phone := payload->>'user_phone';
                v_practitioner_id := (payload->>'practitioner_id')::uuid;
                v_practitioner_title := payload->>'practitioner_title';
                v_specialty_id := (payload->>'specialty_id')::uuid;
                v_practitioner_location_id := (payload->>'practitioner_location_id')::uuid;
                v_membership_id := (payload->>'membership_id')::uuid;
                v_pin_hash := payload->>'pin_hash';
                v_pin_salt := payload->>'pin_salt';
                v_activation_code_id := (payload->>'activation_code_id')::uuid;
                v_activation_code_hash := payload->>'activation_code_hash';

                INSERT INTO organizations (id, name, plan_tier, created_at)
                VALUES (v_org_id, v_org_name, v_plan_tier, v_now);

                INSERT INTO locations (id, org_id, name, address, phone, is_active)
                VALUES (v_location_id, v_org_id, v_location_name, v_location_address, v_location_phone, true);

                SELECT id INTO v_existing_user_id FROM users WHERE phone = v_user_phone;
                IF FOUND THEN
                    v_user_id := v_existing_user_id;
                    v_user_is_new := false;
                ELSE
                    v_user_id := (payload->>'user_id')::uuid;
                    INSERT INTO users (id, full_name, phone, email, is_active)
                    VALUES (v_user_id, v_user_full_name, v_user_phone, NULL, true);
                END IF;

                INSERT INTO practitioners (id, org_id, user_id, full_name, specialty_id, title, is_active)
                VALUES (v_practitioner_id, v_org_id, v_user_id, v_user_full_name, v_specialty_id, v_practitioner_title, true);

                INSERT INTO practitioner_locations (id, practitioner_id, location_id, is_active)
                VALUES (v_practitioner_location_id, v_practitioner_id, v_location_id, true);

                INSERT INTO memberships (
                    id, user_id, org_id, role, location_scope, practitioner_scope,
                    practitioner_id, pin_hash, pin_salt, is_active
                )
                VALUES (
                    v_membership_id, v_user_id, v_org_id,
                    'owner', 'all', 'all', NULL,
                    v_pin_hash, v_pin_salt, true
                );

                INSERT INTO activation_codes (id, org_id, location_id, code_hash, expires_at, used_at, used_by_device_id, created_at)
                VALUES (v_activation_code_id, v_org_id, v_location_id, v_activation_code_hash, v_activation_code_expires_at, NULL, NULL, v_now);

                SELECT COALESCE(MAX(seq), 0) INTO v_seq FROM audit_log;

                v_seq := v_seq + 1;
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_organization_id')::uuid, v_org_id, v_membership_id, 'organizations', v_org_id, 'create', NULL,
                    jsonb_build_object('id', v_org_id, 'name', v_org_name, 'plan_tier', v_plan_tier, 'created_at', v_now),
                    v_now, v_seq
                );

                v_seq := v_seq + 1;
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_location_id')::uuid, v_org_id, v_membership_id, 'locations', v_location_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_location_id, 'org_id', v_org_id, 'name', v_location_name,
                        'address', v_location_address, 'phone', v_location_phone, 'is_active', true
                    ),
                    v_now, v_seq
                );

                IF v_user_is_new THEN
                    v_seq := v_seq + 1;
                    INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                    VALUES (
                        (payload->>'audit_user_id')::uuid, v_org_id, v_membership_id, 'users', v_user_id, 'create', NULL,
                        jsonb_build_object('id', v_user_id, 'full_name', v_user_full_name, 'phone', v_user_phone, 'email', NULL, 'is_active', true),
                        v_now, v_seq
                    );
                END IF;

                v_seq := v_seq + 1;
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_practitioner_id')::uuid, v_org_id, v_membership_id, 'practitioners', v_practitioner_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_practitioner_id, 'org_id', v_org_id, 'user_id', v_user_id, 'full_name', v_user_full_name,
                        'specialty_id', v_specialty_id, 'title', v_practitioner_title, 'is_active', true
                    ),
                    v_now, v_seq
                );

                v_seq := v_seq + 1;
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_practitioner_location_id')::uuid, v_org_id, v_membership_id, 'practitioner_locations', v_practitioner_location_id, 'create', NULL,
                    jsonb_build_object('id', v_practitioner_location_id, 'practitioner_id', v_practitioner_id, 'location_id', v_location_id, 'is_active', true),
                    v_now, v_seq
                );

                v_seq := v_seq + 1;
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_membership_id')::uuid, v_org_id, v_membership_id, 'memberships', v_membership_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_membership_id, 'user_id', v_user_id, 'org_id', v_org_id, 'role', 'owner',
                        'location_scope', 'all', 'practitioner_scope', 'all', 'practitioner_id', NULL, 'is_active', true
                    ),
                    v_now, v_seq
                );

                v_seq := v_seq + 1;
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_activation_code_id')::uuid, v_org_id, v_membership_id, 'activation_codes', v_activation_code_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_activation_code_id, 'org_id', v_org_id, 'location_id', v_location_id,
                        'expires_at', v_activation_code_expires_at, 'used_at', NULL, 'used_by_device_id', NULL
                    ),
                    v_now, v_seq
                );

                RETURN jsonb_build_object(
                    'organization_id', v_org_id,
                    'location_id', v_location_id,
                    'user_id', v_user_id,
                    'user_is_new', v_user_is_new,
                    'practitioner_id', v_practitioner_id,
                    'practitioner_location_id', v_practitioner_location_id,
                    'membership_id', v_membership_id,
                    'activation_code_id', v_activation_code_id
                );
            END;
            $$
        SQL);
        DB::statement('REVOKE EXECUTE ON FUNCTION provision_organization(jsonb) FROM PUBLIC');
        DB::statement('GRANT EXECUTE ON FUNCTION provision_organization(jsonb) TO clintra_owner');
        DB::statement('RESET ROLE');

        DB::statement('SET ROLE clintra_mint');
        DB::statement('DROP FUNCTION IF EXISTS mint_activation_code(jsonb)');
        DB::statement(<<<'SQL'
            CREATE FUNCTION mint_activation_code(payload jsonb) RETURNS jsonb
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = public, pg_temp
            AS $$
            DECLARE
                v_allowed_keys text[] := ARRAY['id', 'org_id', 'location_id', 'code_hash', 'expires_at', 'audit_id'];
                v_unknown_keys text[];
                v_key text;

                v_id uuid;
                v_org_id uuid;
                v_location_id uuid;
                v_code_hash text;
                v_expires_at timestamptz;
                v_owner_membership_id uuid;
                v_seq bigint;
                v_now timestamptz := now();
            BEGIN
                SELECT array_agg(k) INTO v_unknown_keys
                FROM jsonb_object_keys(payload) AS k
                WHERE k <> ALL (v_allowed_keys);

                IF v_unknown_keys IS NOT NULL THEN
                    RAISE EXCEPTION 'mint_activation_code: unknown payload key(s): %', array_to_string(v_unknown_keys, ', ')
                        USING ERRCODE = '22023';
                END IF;

                FOREACH v_key IN ARRAY v_allowed_keys LOOP
                    IF NOT jsonb_exists(payload, v_key) OR jsonb_typeof(payload -> v_key) = 'null' THEN
                        RAISE EXCEPTION 'mint_activation_code: missing or null required key "%"', v_key
                            USING ERRCODE = '22023';
                    END IF;
                END LOOP;

                v_org_id := (payload->>'org_id')::uuid;
                v_location_id := (payload->>'location_id')::uuid;
                v_code_hash := payload->>'code_hash';
                v_expires_at := (payload->>'expires_at')::timestamptz;

                IF v_code_hash !~ '^[0-9a-f]{64}$' THEN
                    RAISE EXCEPTION 'mint_activation_code: code_hash must be 64 lowercase hex characters' USING ERRCODE = '22023';
                END IF;

                IF v_expires_at <= v_now THEN
                    RAISE EXCEPTION 'mint_activation_code: expires_at must be in the future' USING ERRCODE = '22023';
                END IF;

                IF NOT EXISTS (SELECT 1 FROM locations WHERE id = v_location_id AND org_id = v_org_id) THEN
                    RAISE EXCEPTION 'mint_activation_code: location_id must belong to org_id' USING ERRCODE = '22023';
                END IF;

                SELECT id INTO v_owner_membership_id
                FROM memberships
                WHERE org_id = v_org_id AND role = 'owner' AND is_active = true
                ORDER BY id
                LIMIT 1;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'mint_activation_code: org_id has no active owner membership' USING ERRCODE = '22023';
                END IF;

                v_id := (payload->>'id')::uuid;

                INSERT INTO activation_codes (id, org_id, location_id, code_hash, expires_at, used_at, used_by_device_id, created_at)
                VALUES (v_id, v_org_id, v_location_id, v_code_hash, v_expires_at, NULL, NULL, v_now);

                SELECT COALESCE(MAX(seq), 0) INTO v_seq FROM audit_log;
                v_seq := v_seq + 1;

                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_id')::uuid, v_org_id, v_owner_membership_id, 'activation_codes', v_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_id, 'org_id', v_org_id, 'location_id', v_location_id,
                        'expires_at', v_expires_at, 'used_at', NULL, 'used_by_device_id', NULL
                    ),
                    v_now, v_seq
                );

                RETURN jsonb_build_object('id', v_id, 'org_id', v_org_id, 'location_id', v_location_id, 'expires_at', v_expires_at);
            END;
            $$
        SQL);
        DB::statement('REVOKE EXECUTE ON FUNCTION mint_activation_code(jsonb) FROM PUBLIC');
        DB::statement('GRANT EXECUTE ON FUNCTION mint_activation_code(jsonb) TO clintra_owner');
        DB::statement('RESET ROLE');

        DB::statement('SET ROLE clintra_register');
        DB::statement('DROP FUNCTION IF EXISTS register_device(jsonb)');
        DB::statement(<<<'SQL'
            CREATE FUNCTION register_device(payload jsonb) RETURNS jsonb
            LANGUAGE plpgsql
            SECURITY DEFINER
            SET search_path = public, pg_temp
            AS $$
            DECLARE
                v_allowed_keys text[] := ARRAY['device_id', 'phone', 'code_hash', 'audit_device_id', 'audit_code_used_id'];
                v_unknown_keys text[];
                v_key text;

                v_device_id uuid;
                v_phone text;
                v_code_hash text;

                v_code_id uuid;
                v_code_org_id uuid;
                v_code_location_id uuid;
                v_code_expires_at timestamptz;
                v_code_used_at timestamptz;

                v_membership_id uuid;
                v_updated_rows int;
                v_seq bigint;
                v_now timestamptz := now();

                v_organization jsonb;
                v_locations jsonb;
                v_practitioners jsonb;
                v_memberships jsonb;
            BEGIN
                IF payload->>'device_id' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
                    RAISE EXCEPTION 'register_device: device_id must be a well-formed uuid' USING ERRCODE = '22023';
                END IF;

                IF payload->>'phone' !~ '^\+[1-9]\d{1,14}$' THEN
                    RAISE EXCEPTION 'register_device: phone must be a non-empty E.164 number' USING ERRCODE = '22023';
                END IF;

                IF payload->>'code_hash' !~ '^[0-9a-f]{64}$' THEN
                    RAISE EXCEPTION 'register_device: code_hash must be 64 lowercase hex characters' USING ERRCODE = '22023';
                END IF;

                SELECT array_agg(k) INTO v_unknown_keys
                FROM jsonb_object_keys(payload) AS k
                WHERE k <> ALL (v_allowed_keys);

                IF v_unknown_keys IS NOT NULL THEN
                    RAISE EXCEPTION 'register_device: unknown payload key(s): %', array_to_string(v_unknown_keys, ', ')
                        USING ERRCODE = '22023';
                END IF;

                FOREACH v_key IN ARRAY v_allowed_keys LOOP
                    IF NOT jsonb_exists(payload, v_key) OR jsonb_typeof(payload -> v_key) = 'null' THEN
                        RAISE EXCEPTION 'register_device: missing or null required key "%"', v_key
                            USING ERRCODE = '22023';
                    END IF;
                END LOOP;

                v_device_id := (payload->>'device_id')::uuid;
                v_phone := payload->>'phone';
                v_code_hash := payload->>'code_hash';

                SELECT id, org_id, location_id, expires_at, used_at
                INTO v_code_id, v_code_org_id, v_code_location_id, v_code_expires_at, v_code_used_at
                FROM activation_codes
                WHERE code_hash = v_code_hash;

                IF NOT FOUND OR v_code_used_at IS NOT NULL OR v_code_expires_at <= v_now THEN
                    RAISE EXCEPTION 'register_device: registration failed';
                END IF;

                SELECT m.id INTO v_membership_id
                FROM memberships m
                JOIN users u ON u.id = m.user_id
                WHERE m.org_id = v_code_org_id
                  AND m.role = 'owner'
                  AND m.is_active = true
                  AND u.phone = v_phone
                LIMIT 1;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'register_device: registration failed';
                END IF;

                UPDATE activation_codes
                SET used_at = v_now
                WHERE id = v_code_id AND used_at IS NULL;

                GET DIAGNOSTICS v_updated_rows = ROW_COUNT;
                IF v_updated_rows = 0 THEN
                    RAISE EXCEPTION 'register_device: registration failed';
                END IF;

                INSERT INTO device (id, org_id, location_id, membership_id, registered_at)
                VALUES (v_device_id, v_code_org_id, v_code_location_id, v_membership_id, v_now);

                UPDATE activation_codes
                SET used_by_device_id = v_device_id
                WHERE id = v_code_id;

                SELECT COALESCE(MAX(seq), 0) INTO v_seq FROM audit_log;

                v_seq := v_seq + 1;
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_device_id')::uuid, v_code_org_id, v_membership_id, 'device', v_device_id, 'create', NULL,
                    jsonb_build_object(
                        'id', v_device_id, 'org_id', v_code_org_id, 'location_id', v_code_location_id,
                        'membership_id', v_membership_id, 'registered_at', v_now
                    ),
                    v_now, v_seq
                );

                v_seq := v_seq + 1;
                INSERT INTO audit_log (id, org_id, actor_membership_id, entity, entity_id, action, before, after, at, seq)
                VALUES (
                    (payload->>'audit_code_used_id')::uuid, v_code_org_id, v_membership_id, 'activation_codes', v_code_id, 'update',
                    jsonb_build_object('used_at', NULL, 'used_by_device_id', NULL),
                    jsonb_build_object('used_at', v_now, 'used_by_device_id', v_device_id),
                    v_now, v_seq
                );

                SELECT jsonb_build_object('id', id, 'name', name, 'plan_tier', plan_tier, 'created_at', created_at)
                INTO v_organization
                FROM organizations WHERE id = v_code_org_id;

                SELECT COALESCE(jsonb_agg(jsonb_build_object(
                    'id', id, 'org_id', org_id, 'name', name, 'address', address, 'phone', phone, 'is_active', is_active
                )), '[]'::jsonb)
                INTO v_locations
                FROM locations WHERE org_id = v_code_org_id;

                SELECT COALESCE(jsonb_agg(jsonb_build_object(
                    'id', id, 'org_id', org_id, 'user_id', user_id, 'full_name', full_name,
                    'specialty_id', specialty_id, 'title', title, 'is_active', is_active
                )), '[]'::jsonb)
                INTO v_practitioners
                FROM practitioners WHERE org_id = v_code_org_id;

                SELECT COALESCE(jsonb_agg(jsonb_build_object(
                    'id', id, 'user_id', user_id, 'org_id', org_id, 'role', role,
                    'location_scope', location_scope, 'practitioner_scope', practitioner_scope,
                    'practitioner_id', practitioner_id, 'pin_hash', pin_hash, 'pin_salt', pin_salt,
                    'is_active', is_active
                )), '[]'::jsonb)
                INTO v_memberships
                FROM memberships WHERE org_id = v_code_org_id;

                RETURN jsonb_build_object(
                    'device_id', v_device_id,
                    'org_id', v_code_org_id,
                    'location_id', v_code_location_id,
                    'membership_id', v_membership_id,
                    'organization', v_organization,
                    'locations', v_locations,
                    'practitioners', v_practitioners,
                    'memberships', v_memberships
                );
            END;
            $$
        SQL);
        DB::statement('REVOKE EXECUTE ON FUNCTION register_device(jsonb) FROM PUBLIC');
        DB::statement('GRANT EXECUTE ON FUNCTION register_device(jsonb) TO clintra_app');
        DB::statement('RESET ROLE');
    }
};
